// <auto-generated />
using System;
using DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(MedicalContext))]
    [Migration("20250722013927_AddVaccineTable")]
    partial class AddVaccineTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DB.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentID");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasKey("AppointmentId")
                        .HasName("PK__Appointm__8ECDFCA24A1FE88D");

                    b.HasIndex("ParentId");

                    b.HasIndex("StaffId");

                    b.HasIndex("StudentId");

                    b.ToTable("Appointment", (string)null);
                });

            modelBuilder.Entity("DB.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BlogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogId"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("StaffUsername")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BlogId")
                        .HasName("PK__Blog__54379E30A73F0B1A");

                    b.HasIndex("StaffUsername");

                    b.ToTable("Blog", (string)null);
                });

            modelBuilder.Entity("DB.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClassRoom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClassTeacher")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrentStudentCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GradeLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MaxStudents")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("ClassId")
                        .HasName("PK__Class__CB1927C0123456789");

                    b.HasIndex(new[] { "ClassName", "GradeLevel", "Section" }, "UQ__Class__Name_Grade_Section")
                        .IsUnique()
                        .HasFilter("[Section] IS NOT NULL");

                    b.ToTable("Class", (string)null);
                });

            modelBuilder.Entity("DB.DashboardSummary", b =>
                {
                    b.Property<int>("SummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SummaryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SummaryId"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    b.Property<int?>("CompletedAppointments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("GeneratedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("HealthCheckFormId")
                        .HasColumnType("int")
                        .HasColumnName("HealthCheckFormID");

                    b.Property<decimal?>("HealthCheckParticipationRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("HealthEventId")
                        .HasColumnType("int")
                        .HasColumnName("HealthEventID");

                    b.Property<int?>("InjectionFormId")
                        .HasColumnType("int")
                        .HasColumnName("InjectionFormID");

                    b.Property<decimal?>("InjectionParticipationRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("MedicineId")
                        .HasColumnType("int")
                        .HasColumnName("MedicineID");

                    b.Property<int?>("MedicineRequestId")
                        .HasColumnType("int")
                        .HasColumnName("MedicineRequestID");

                    b.Property<int?>("ScheduledAppointments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    b.Property<int?>("SupplyId")
                        .HasColumnType("int")
                        .HasColumnName("SupplyID");

                    b.Property<int?>("TotalAppointments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("TotalHealthCheckNonParticipants")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("TotalHealthCheckParticipants")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("TotalHealthEvents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("TotalInjectionNonParticipants")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("TotalInjectionParticipants")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("TotalMedicineItems")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("TotalMedicineRequests")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("TotalSupplyItems")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("SummaryId")
                        .HasName("PK__Dashboar__DAB10E0FE883130D");

                    b.HasIndex("StaffId");

                    b.ToTable("Dashboard_Summary", (string)null);
                });

            modelBuilder.Entity("DB.GradeNurse", b =>
                {
                    b.Property<int>("GradeNurseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GradeNurseId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeNurseId"));

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("GradeNurseId");

                    b.HasIndex("StaffId");

                    b.ToTable("GradeNurse", (string)null);
                });

            modelBuilder.Entity("DB.HealthCheckForm", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FormID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormId"));

                    b.Property<bool?>("AutoAdvance")
                        .HasColumnType("bit");

                    b.Property<string>("ClassName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConfirmStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("ConfirmedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConfirmedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ConsentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ConsentStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstimatedDuration")
                        .HasColumnType("int");

                    b.Property<string>("EstimatedEndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("GenerateReport")
                        .HasColumnType("bit");

                    b.Property<string>("GradeIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GradeLevel")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("NotifyParents")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentID");

                    b.Property<bool?>("RequireParentConfirmation")
                        .HasColumnType("bit");

                    b.Property<bool?>("SaveResults")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SelectedStations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffAssigned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalStudents")
                        .HasColumnType("int");

                    b.HasKey("FormId")
                        .HasName("PK__Health_C__FB05B7BD3533D90A");

                    b.HasIndex("ConfirmedBy");

                    b.HasIndex("ParentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Health_Check_Form", (string)null);
                });

            modelBuilder.Entity("DB.HealthCheckItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EstimatedTimeMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("ItemId")
                        .HasName("PK_HealthCheckItem");

                    b.HasIndex(new[] { "Code" }, "IX_HealthCheckItem_Code")
                        .IsUnique();

                    b.ToTable("HealthCheckItem", (string)null);
                });

            modelBuilder.Entity("DB.HealthCheckItemMedicalSupply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HealthCheckItemId")
                        .HasColumnType("int")
                        .HasColumnName("HealthCheckItemID");

                    b.Property<bool>("IsOptional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MedicalSupplyId")
                        .HasColumnType("int")
                        .HasColumnName("MedicalSupplyID");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("QuantityRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(1m);

                    b.HasKey("Id")
                        .HasName("PK_HealthCheckItemMedicalSupply");

                    b.HasIndex("HealthCheckItemId");

                    b.HasIndex("MedicalSupplyId");

                    b.ToTable("HealthCheckItemMedicalSupply", (string)null);
                });

            modelBuilder.Entity("DB.HealthCheckResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ResultID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<string>("BloodPressure")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ExaminedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExaminedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("FormId")
                        .HasColumnType("int")
                        .HasColumnName("FormID");

                    b.Property<string>("GeneralFindings")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HearingStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("HeartRate")
                        .HasColumnType("int");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Recommendations")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<string>("VisionLeft")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VisionRight")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("ResultId")
                        .HasName("PK__Health_C__97690228CF51D4A0");

                    b.HasIndex("ExaminedBy");

                    b.HasIndex("FormId");

                    b.HasIndex("StudentId");

                    b.ToTable("Health_Check_Result", (string)null);
                });

            modelBuilder.Entity("DB.HealthEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EventID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Assessment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EventDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("FollowUpRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("ParentNotified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    b.Property<string>("StudentCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Symptoms")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Treatment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("EventId")
                        .HasName("PK__Health_E__7944C870BB836071");

                    b.HasIndex("StaffId");

                    b.HasIndex("StudentCode");

                    b.ToTable("Health_Event", (string)null);
                });

            modelBuilder.Entity("DB.HealthEventMedicalSupply", b =>
                {
                    b.Property<int>("HealthEventMedicalSupplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HealthEventMedicalSupplyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthEventMedicalSupplyId"));

                    b.Property<int>("HealthEventId")
                        .HasColumnType("int")
                        .HasColumnName("HealthEventID");

                    b.Property<int>("MedicalSupplyId")
                        .HasColumnType("int")
                        .HasColumnName("MedicalSupplyID");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Time")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("HealthEventMedicalSupplyId");

                    b.HasIndex("HealthEventId");

                    b.HasIndex("MedicalSupplyId");

                    b.ToTable("Health_Event_Medical_Supply", (string)null);
                });

            modelBuilder.Entity("DB.HealthEventMedicine", b =>
                {
                    b.Property<int>("HealthEventMedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HealthEventMedicineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthEventMedicineId"));

                    b.Property<string>("Dosage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HealthEventId")
                        .HasColumnType("int")
                        .HasColumnName("HealthEventID");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int")
                        .HasColumnName("MedicineID");

                    b.Property<string>("Time")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("HealthEventMedicineId");

                    b.HasIndex("HealthEventId");

                    b.HasIndex("MedicineId");

                    b.ToTable("Health_Event_Medicine", (string)null);
                });

            modelBuilder.Entity("DB.HealthProfile", b =>
                {
                    b.Property<int>("HealthProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HealthProfileID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthProfileId"));

                    b.Property<string>("AllergyDetails")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("BloodPressure")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BloodType")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("ChronicDetails")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EmergencyContact")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("HasAllergies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("HasChronicDiseases")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("HasCompleteVaccinations")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<bool?>("HasHearingIssues")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("HasPreviousTreatment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("HasVisionIssues")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("HearingNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("HeartRate")
                        .HasColumnType("int");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("LeftEar")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LeftEye")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OtherInfo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RightEar")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RightEye")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TreatmentDetails")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("VaccinationDetails")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Vaccinations")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("VisionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("HealthProfileId")
                        .HasName("PK__Health_P__73C2C2B5FF5B2341");

                    b.HasIndex("StudentCode");

                    b.ToTable("Health_Profile", (string)null);
                });

            modelBuilder.Entity("DB.InjectionForm", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FormID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormId"));

                    b.Property<string>("ClassName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConfirmStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("ConfirmedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConfirmedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ConsentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ConsentStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("GradeLevel")
                        .HasColumnType("int");

                    b.Property<string>("InjectionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentID");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<int?>("VaccineId")
                        .HasColumnType("int");

                    b.HasKey("FormId")
                        .HasName("PK__Injectio__FB05B7BDEC6DF4D0");

                    b.HasIndex("ConfirmedBy");

                    b.HasIndex("ParentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("VaccineId");

                    b.ToTable("Injection_Form", (string)null);
                });

            modelBuilder.Entity("DB.InjectionResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ResultID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<int?>("AdministeredBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("AdministeredDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FollowUpNotes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("FollowUpRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("FormId")
                        .HasColumnType("int")
                        .HasColumnName("FormID");

                    b.Property<string>("ImmediateReaction")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasKey("ResultId")
                        .HasName("PK__Injectio__9769022834983DA5");

                    b.HasIndex("AdministeredBy");

                    b.HasIndex("FormId");

                    b.HasIndex("StudentId");

                    b.ToTable("Injection_Result", (string)null);
                });

            modelBuilder.Entity("DB.MedicalSupply", b =>
                {
                    b.Property<int>("SupplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SupplyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplyId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.HasKey("SupplyId")
                        .HasName("PK__Medical___7CDD6C8E0BF90B60");

                    b.ToTable("Medical_Supply", (string)null);
                });

            modelBuilder.Entity("DB.Medicine", b =>
                {
                    b.Property<int>("MedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedicineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicineId"));

                    b.Property<string>("AdministrationMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dose")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MedicineId")
                        .HasName("PK__Medicine__4F2128F091736C4F");

                    b.ToTable("Medicine", (string)null);
                });

            modelBuilder.Entity("DB.MedicineRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("ClassName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentID");

                    b.Property<string>("RefusalReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("StudentCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("RequestId")
                        .HasName("PK__Medicine__33A8519AA6EED751");

                    b.HasIndex("ParentId");

                    b.HasIndex("StaffId");

                    b.HasIndex("StudentCode");

                    b.ToTable("Medicine_Request", (string)null);
                });

            modelBuilder.Entity("DB.MedicineRequestItem", b =>
                {
                    b.Property<int>("MedicineRequestItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedicineRequestItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicineRequestItemId"));

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DosageUnit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Instructions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MedicineRequestId")
                        .HasColumnType("int")
                        .HasColumnName("MedicineRequestID");

                    b.Property<string>("Period")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeOfDay")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedicineRequestItemId");

                    b.HasIndex("MedicineRequestId");

                    b.ToTable("Medicine_Request_Item", (string)null);
                });

            modelBuilder.Entity("DB.Parent", b =>
                {
                    b.Property<int>("ParentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ParentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParentId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsEmergencyContact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsMainContact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ParentId")
                        .HasName("PK__Parent__D339510FC35C248C");

                    b.ToTable("Parent", (string)null);
                });

            modelBuilder.Entity("DB.RequestResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ResultID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<int?>("ActionBy")
                        .HasColumnType("int")
                        .HasColumnName("ActionBy");

                    b.Property<int?>("AdministeredBy")
                        .HasColumnType("int")
                        .HasColumnName("AdministeredBy");

                    b.Property<string>("AdministeredFrequencies")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("AdministeredTime")
                        .HasColumnType("datetime");

                    b.Property<DateOnly?>("CurrentDate")
                        .HasColumnType("date");

                    b.Property<int?>("CurrentDayCount")
                        .HasColumnType("int");

                    b.Property<int?>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("FailedFrequencies")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FailureReasons")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Frequency")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsReRequest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastAttemptTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("OriginalRequestResultId")
                        .HasColumnType("int")
                        .HasColumnName("OriginalRequestResultID");

                    b.Property<string>("ReRequestReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("TimesPerDay")
                        .HasColumnType("int");

                    b.HasKey("ResultId")
                        .HasName("PK__Request___97690228392A5FD6");

                    b.HasIndex("ActionBy");

                    b.HasIndex("AdministeredBy");

                    b.HasIndex("OriginalRequestResultId");

                    b.HasIndex("RequestId");

                    b.ToTable("Request_Result", (string)null);
                });

            modelBuilder.Entity("DB.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<int>("Permissions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("0");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE1A12345678");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Role__8A2B616058FE1837")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("DB.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActiveForRequest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("StaffId")
                        .HasName("PK__Staff__96D4AAF731254C53");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Username" }, "UQ__Staff__536C85E4FC5C7093")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Staff__A9D10534AFE18051")
                        .IsUnique();

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("DB.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("StudentId")
                        .HasName("PK__Student__32C52A7964894850");

                    b.HasIndex("ClassId");

                    b.HasIndex(new[] { "StudentCode" }, "UQ__Student__1FC8860437093A19")
                        .IsUnique();

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("DB.StudentParent", b =>
                {
                    b.Property<int>("StudentParentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StudentParentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentParentId"));

                    b.Property<int>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentID");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("StudentParentId");

                    b.HasIndex("ParentId");

                    b.HasIndex("StudentCode");

                    b.ToTable("Student_Parent", (string)null);
                });

            modelBuilder.Entity("DB.Vaccine", b =>
                {
                    b.Property<int>("VaccineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaccineId"));

                    b.Property<string>("AdministrationMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Dose")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VaccineId");

                    b.ToTable("Vaccine", (string)null);
                });

            modelBuilder.Entity("DB.Appointment", b =>
                {
                    b.HasOne("DB.Parent", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("DB.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId");

                    b.HasOne("DB.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("Parent");

                    b.Navigation("Staff");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DB.Blog", b =>
                {
                    b.HasOne("DB.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffUsername")
                        .HasPrincipalKey("Username")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Blog__StaffUsername");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DB.DashboardSummary", b =>
                {
                    b.HasOne("DB.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK__Dashboard_Summary__StaffID");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DB.GradeNurse", b =>
                {
                    b.HasOne("DB.Staff", "Nurse")
                        .WithMany("GradeNurses")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nurse");
                });

            modelBuilder.Entity("DB.HealthCheckForm", b =>
                {
                    b.HasOne("DB.Staff", "ConfirmedByStaff")
                        .WithMany()
                        .HasForeignKey("ConfirmedBy")
                        .HasConstraintName("FK__Health_Check_Form__ConfirmedBy");

                    b.HasOne("DB.Parent", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK__Health_Check_Form__ParentID");

                    b.HasOne("DB.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Health_Check_Form__StudentID");

                    b.Navigation("ConfirmedByStaff");

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DB.HealthCheckItemMedicalSupply", b =>
                {
                    b.HasOne("DB.HealthCheckItem", "HealthCheckItem")
                        .WithMany("HealthCheckItemMedicalSupplies")
                        .HasForeignKey("HealthCheckItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HealthCheckItemMedicalSupply_HealthCheckItem");

                    b.HasOne("DB.MedicalSupply", "MedicalSupply")
                        .WithMany()
                        .HasForeignKey("MedicalSupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HealthCheckItemMedicalSupply_MedicalSupply");

                    b.Navigation("HealthCheckItem");

                    b.Navigation("MedicalSupply");
                });

            modelBuilder.Entity("DB.HealthCheckResult", b =>
                {
                    b.HasOne("DB.Staff", "ExaminedByStaff")
                        .WithMany()
                        .HasForeignKey("ExaminedBy")
                        .HasConstraintName("FK__Health_Check_Result__ExaminedBy");

                    b.HasOne("DB.HealthCheckForm", "Form")
                        .WithMany("Results")
                        .HasForeignKey("FormId")
                        .HasConstraintName("FK__Health_Check_Result__FormID");

                    b.HasOne("DB.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Health_Check_Result__StudentID");

                    b.Navigation("ExaminedByStaff");

                    b.Navigation("Form");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DB.HealthEvent", b =>
                {
                    b.HasOne("DB.Staff", "Staff")
                        .WithMany("HealthEvents")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Health_Event__StaffID");

                    b.HasOne("DB.Student", "Student")
                        .WithMany("HealthEvents")
                        .HasForeignKey("StudentCode")
                        .HasPrincipalKey("StudentCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Health_Event__StudentCode");

                    b.Navigation("Staff");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DB.HealthEventMedicalSupply", b =>
                {
                    b.HasOne("DB.HealthEvent", "HealthEvent")
                        .WithMany("HealthEventMedicalSupplies")
                        .HasForeignKey("HealthEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Health_Event_Medical_Supply__HealthEventID");

                    b.HasOne("DB.MedicalSupply", "MedicalSupply")
                        .WithMany()
                        .HasForeignKey("MedicalSupplyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK__Health_Event_Medical_Supply__MedicalSupplyID");

                    b.Navigation("HealthEvent");

                    b.Navigation("MedicalSupply");
                });

            modelBuilder.Entity("DB.HealthEventMedicine", b =>
                {
                    b.HasOne("DB.HealthEvent", "HealthEvent")
                        .WithMany("HealthEventMedicines")
                        .HasForeignKey("HealthEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Health_Event_Medicine__HealthEventID");

                    b.HasOne("DB.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK__Health_Event_Medicine__MedicineID");

                    b.Navigation("HealthEvent");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("DB.HealthProfile", b =>
                {
                    b.HasOne("DB.Student", "Student")
                        .WithMany("HealthProfiles")
                        .HasForeignKey("StudentCode")
                        .HasPrincipalKey("StudentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Health_Profile__StudentCode");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DB.InjectionForm", b =>
                {
                    b.HasOne("DB.Staff", "ConfirmedByStaff")
                        .WithMany()
                        .HasForeignKey("ConfirmedBy")
                        .HasConstraintName("FK__Injection_Form__ConfirmedBy");

                    b.HasOne("DB.Parent", "Parent")
                        .WithMany("InjectionForms")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK__Injection_Form__ParentID");

                    b.HasOne("DB.Student", "Student")
                        .WithMany("InjectionForms")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Injection_Form__StudentID");

                    b.HasOne("DB.Vaccine", "Vaccine")
                        .WithMany()
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_InjectionForm_Vaccine");

                    b.Navigation("ConfirmedByStaff");

                    b.Navigation("Parent");

                    b.Navigation("Student");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("DB.InjectionResult", b =>
                {
                    b.HasOne("DB.Staff", "AdministeredByStaff")
                        .WithMany()
                        .HasForeignKey("AdministeredBy")
                        .HasConstraintName("FK__Injection_Result__AdministeredBy");

                    b.HasOne("DB.InjectionForm", "Form")
                        .WithMany("InjectionResults")
                        .HasForeignKey("FormId")
                        .HasConstraintName("FK__Injection_Result__FormID");

                    b.HasOne("DB.Student", "Student")
                        .WithMany("InjectionResults")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Injection_Result__StudentID");

                    b.Navigation("AdministeredByStaff");

                    b.Navigation("Form");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DB.MedicineRequest", b =>
                {
                    b.HasOne("DB.Parent", "Parent")
                        .WithMany("MedicineRequests")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK__Medicine_Request__ParentID");

                    b.HasOne("DB.Staff", "Staff")
                        .WithMany("MedicineRequests")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK__Medicine_Request__StaffID");

                    b.HasOne("DB.Student", "Student")
                        .WithMany("MedicineRequests")
                        .HasForeignKey("StudentCode")
                        .HasPrincipalKey("StudentCode")
                        .HasConstraintName("FK__Medicine_Request__StudentCode");

                    b.Navigation("Parent");

                    b.Navigation("Staff");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DB.MedicineRequestItem", b =>
                {
                    b.HasOne("DB.MedicineRequest", "MedicineRequest")
                        .WithMany("MedicineRequestItems")
                        .HasForeignKey("MedicineRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Medicine_Request_Item__MedicineRequestID");

                    b.Navigation("MedicineRequest");
                });

            modelBuilder.Entity("DB.RequestResult", b =>
                {
                    b.HasOne("DB.Staff", "ActionByStaff")
                        .WithMany("ActionedRequestResults")
                        .HasForeignKey("ActionBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK__Request_Result__ActionBy");

                    b.HasOne("DB.Staff", "AdministeredByStaff")
                        .WithMany("AdministeredRequestResults")
                        .HasForeignKey("AdministeredBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK__Request_Result__AdministeredBy");

                    b.HasOne("DB.RequestResult", "OriginalRequestResult")
                        .WithMany("ReRequests")
                        .HasForeignKey("OriginalRequestResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK__Request_Result__OriginalRequestResultID");

                    b.HasOne("DB.MedicineRequest", "Request")
                        .WithMany("RequestResults")
                        .HasForeignKey("RequestId")
                        .HasConstraintName("FK__Request_Result__RequestID");

                    b.Navigation("ActionByStaff");

                    b.Navigation("AdministeredByStaff");

                    b.Navigation("OriginalRequestResult");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("DB.Staff", b =>
                {
                    b.HasOne("DB.Role", "Role")
                        .WithMany("Staff")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DB.Student", b =>
                {
                    b.HasOne("DB.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Student__ClassID");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("DB.StudentParent", b =>
                {
                    b.HasOne("DB.Parent", "Parent")
                        .WithMany("StudentParents")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_StudentParent_Parent");

                    b.HasOne("DB.Student", "Student")
                        .WithMany("StudentParents")
                        .HasForeignKey("StudentCode")
                        .HasPrincipalKey("StudentCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_StudentParent_Student");

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DB.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("DB.HealthCheckForm", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("DB.HealthCheckItem", b =>
                {
                    b.Navigation("HealthCheckItemMedicalSupplies");
                });

            modelBuilder.Entity("DB.HealthEvent", b =>
                {
                    b.Navigation("HealthEventMedicalSupplies");

                    b.Navigation("HealthEventMedicines");
                });

            modelBuilder.Entity("DB.InjectionForm", b =>
                {
                    b.Navigation("InjectionResults");
                });

            modelBuilder.Entity("DB.MedicineRequest", b =>
                {
                    b.Navigation("MedicineRequestItems");

                    b.Navigation("RequestResults");
                });

            modelBuilder.Entity("DB.Parent", b =>
                {
                    b.Navigation("InjectionForms");

                    b.Navigation("MedicineRequests");

                    b.Navigation("StudentParents");
                });

            modelBuilder.Entity("DB.RequestResult", b =>
                {
                    b.Navigation("ReRequests");
                });

            modelBuilder.Entity("DB.Role", b =>
                {
                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DB.Staff", b =>
                {
                    b.Navigation("ActionedRequestResults");

                    b.Navigation("AdministeredRequestResults");

                    b.Navigation("GradeNurses");

                    b.Navigation("HealthEvents");

                    b.Navigation("MedicineRequests");
                });

            modelBuilder.Entity("DB.Student", b =>
                {
                    b.Navigation("HealthEvents");

                    b.Navigation("HealthProfiles");

                    b.Navigation("InjectionForms");

                    b.Navigation("InjectionResults");

                    b.Navigation("MedicineRequests");

                    b.Navigation("StudentParents");
                });
#pragma warning restore 612, 618
        }
    }
}
