using AutoMapper;
using DB;
using API.DTOs;
using System.Security.Cryptography;
using System.Text;
using System.Linq;

namespace API.MappingProfiles;

public class ParentProfile : Profile
{
    public ParentProfile()
    {
        // Map from Parent to ParentDto.ViewModel
        CreateMap<Parent, ParentDto.ViewModel>()
            .ForMember(dest => dest.Students, opt => opt.MapFrom(src => src.Students))
            .ForMember(dest => dest.StudentParents, opt => opt.MapFrom(src => src.StudentParents))
            .ForMember(dest => dest.StudentCode, opt => opt.MapFrom(src =>
                src.StudentParents != null
                    ? src.StudentParents
                        .Where(sp => sp.Student != null && !string.IsNullOrEmpty(sp.Student.StudentCode))
                        .Select(sp => sp.Student.StudentCode)
                        .FirstOrDefault()
                    : null));

        // Map from Student to ParentDto.StudentSummary
        CreateMap<Student, ParentDto.StudentSummary>();

        // Map from ParentDto.Create to Parent
        CreateMap<ParentDto.Create, Parent>()
            .ForMember(dest => dest.ParentId, opt => opt.Ignore()) // ParentId is generated by DB
            .ForMember(dest => dest.Password, opt => opt.MapFrom(src => HashPassword(src.Password)))
            .ForMember(dest => dest.Students, opt => opt.Ignore()) // Ignore navigation properties
            .ForMember(dest => dest.StudentParents, opt => opt.Ignore())
            .ForMember(dest => dest.MedicineRequests, opt => opt.Ignore())
            .ForMember(dest => dest.InjectionForms, opt => opt.Ignore());

        // Map from ParentDto.Update to Parent
        CreateMap<ParentDto.Update, Parent>()
            .ForMember(dest => dest.Students, opt => opt.Ignore()) // Ignore navigation properties
            .ForMember(dest => dest.StudentParents, opt => opt.Ignore())
            .ForMember(dest => dest.MedicineRequests, opt => opt.Ignore())
            .ForMember(dest => dest.InjectionForms, opt => opt.Ignore())
            .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null)); // Only map non-null properties
    }

    private string HashPassword(string password)
    {
        using (var sha256 = SHA256.Create())
        {
            var hashedBytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(password));
            return Convert.ToBase64String(hashedBytes);
        }
    }
} 