using AutoMapper;
using DB;
using API.DTOs;

namespace API.MappingProfiles;

public class ParentProfile : Profile
{
    public ParentProfile()
    {
        // Map from Parent to ParentDto.ViewModel
        CreateMap<Parent, ParentDto.ViewModel>()
            .ForMember(dest => dest.StudentName, opt => opt.MapFrom(src => 
                src.Student != null ? $"{src.Student.FirstName} {src.Student.LastName}" : null));

        // Map from ParentDto.Create to Parent
        CreateMap<ParentDto.Create, Parent>()
            .ForMember(dest => dest.ParentId, opt => opt.Ignore()) // ParentId is generated by DB
            .ForMember(dest => dest.Student, opt => opt.Ignore()); // Ignore navigation properties

        // Map from ParentDto.Update to Parent
        CreateMap<ParentDto.Update, Parent>()
            .ForMember(dest => dest.Student, opt => opt.Ignore()) // Ignore navigation properties
            .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null)); // Only map non-null properties
    }
} 