using AutoMapper;
using DB;
using API.DTOs;
using System.Security.Cryptography;
using System.Text;

namespace API.MappingProfiles;

public class StudentProfile : Profile
{
    public StudentProfile()
    {
        // Map from Student to StudentDto.ViewModel
        CreateMap<Student, StudentDto.ViewModel>()
            .ForMember(dest => dest.ClassName, opt => opt.MapFrom(src => 
                src.Class != null ? src.Class.ClassName : "Unknown"))
            .ForMember(dest => dest.GradeLevel, opt => opt.MapFrom(src => 
                src.Class != null ? src.Class.GradeLevel : 0))
            .ForMember(dest => dest.HealthProfileCount, opt => opt.MapFrom(src => 
                src.HealthProfiles != null ? src.HealthProfiles.Count : 0))
            .ForMember(dest => dest.HealthEventCount, opt => opt.MapFrom(src => 
                src.HealthEvents != null ? src.HealthEvents.Count : 0))
            .ForMember(dest => dest.ParentCount, opt => opt.MapFrom(src => 
                src.StudentParents != null ? src.StudentParents.Count : 0))
            .ForMember(dest => dest.Parents, opt => opt.MapFrom(src => src.Parents))
            .ForMember(dest => dest.StudentParents, opt => opt.MapFrom(src => src.StudentParents))
            .ForMember(dest => dest.ClassName, opt => opt.MapFrom(src => src.Class != null ? src.Class.ClassName : null))
            .ForMember(dest => dest.GradeLevel, opt => opt.MapFrom(src => src.Class != null ? src.Class.GradeLevel : 0));

        // Map from Parent to StudentDto.ParentSummary
        CreateMap<Parent, StudentDto.ParentSummary>();

        // Map from StudentDto.Create to Student
        CreateMap<StudentDto.Create, Student>()
            .ForMember(dest => dest.StudentId, opt => opt.Ignore()) // StudentId is generated by DB
            .ForMember(dest => dest.Password, opt => opt.MapFrom(src => HashPassword(src.Password)))
            .ForMember(dest => dest.HealthEvents, opt => opt.Ignore()) // Ignore navigation properties
            .ForMember(dest => dest.HealthProfiles, opt => opt.Ignore())
            .ForMember(dest => dest.StudentParents, opt => opt.Ignore())
            .ForMember(dest => dest.Parents, opt => opt.Ignore())
            .ForMember(dest => dest.MedicineRequests, opt => opt.Ignore())
            .ForMember(dest => dest.InjectionForms, opt => opt.Ignore())
            .ForMember(dest => dest.InjectionResults, opt => opt.Ignore());

        // Map from StudentDto.Update to Student
        CreateMap<StudentDto.Update, Student>()
            .ForMember(dest => dest.HealthEvents, opt => opt.Ignore()) // Ignore navigation properties
            .ForMember(dest => dest.HealthProfiles, opt => opt.Ignore())
            .ForMember(dest => dest.StudentParents, opt => opt.Ignore())
            .ForMember(dest => dest.Parents, opt => opt.Ignore())
            .ForMember(dest => dest.MedicineRequests, opt => opt.Ignore())
            .ForMember(dest => dest.InjectionForms, opt => opt.Ignore())
            .ForMember(dest => dest.InjectionResults, opt => opt.Ignore())
            .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null)); // Only map non-null properties
    }

    private string HashPassword(string password)
    {
        using (var sha256 = SHA256.Create())
        {
            var hashedBytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(password));
            return Convert.ToBase64String(hashedBytes);
        }
    }
} 