using AutoMapper;
using DB;
using API.DTOs;

namespace API.MappingProfiles;

public class StudentProfile : Profile
{
    public StudentProfile()
    {
        // Map from Student to StudentDto.ViewModel
        CreateMap<Student, StudentDto.ViewModel>()
            .ForMember(dest => dest.StaffName, opt => opt.MapFrom(src => 
                src.Staff != null ? $"{src.Staff.FirstName} {src.Staff.LastName}" : null))
            .ForMember(dest => dest.HealthProfileCount, opt => opt.MapFrom(src => 
                src.HealthProfiles != null ? src.HealthProfiles.Count : 0))
            .ForMember(dest => dest.HealthEventCount, opt => opt.MapFrom(src => 
                src.HealthEvents != null ? src.HealthEvents.Count : 0))
            .ForMember(dest => dest.ParentCount, opt => opt.MapFrom(src => 
                src.Parents != null ? src.Parents.Count : 0));

        // Map from StudentDto.Create to Student
        CreateMap<StudentDto.Create, Student>()
            .ForMember(dest => dest.StudentId, opt => opt.Ignore()) // StudentId is generated by DB
            .ForMember(dest => dest.HealthEvents, opt => opt.Ignore()) // Ignore navigation properties
            .ForMember(dest => dest.HealthProfiles, opt => opt.Ignore())
            .ForMember(dest => dest.Parents, opt => opt.Ignore())
            .ForMember(dest => dest.Staff, opt => opt.Ignore());

        // Map from StudentDto.Update to Student
        CreateMap<StudentDto.Update, Student>()
            .ForMember(dest => dest.HealthEvents, opt => opt.Ignore()) // Ignore navigation properties
            .ForMember(dest => dest.HealthProfiles, opt => opt.Ignore())
            .ForMember(dest => dest.Parents, opt => opt.Ignore())
            .ForMember(dest => dest.Staff, opt => opt.Ignore())
            .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null)); // Only map non-null properties
    }
} 