using DB;
using Repo;
using OfficeOpenXml;

namespace Service;

public class DashboardSummaryService : IDashboardSummaryService
{
    private readonly IDashboardSummaryRepository _dashboardSummaryRepository;
    private readonly IStaffRepository _staffRepository;

    public DashboardSummaryService(
        IDashboardSummaryRepository dashboardSummaryRepository,
        IStaffRepository staffRepository)
    {
        _dashboardSummaryRepository = dashboardSummaryRepository;
        _staffRepository = staffRepository;
    }

    public async Task<IEnumerable<DashboardSummary>> GetAllDashboardSummariesAsync()
    {
        return await _dashboardSummaryRepository.GetAllDashboardSummariesAsync();
    }

    public async Task<DashboardSummary?> GetDashboardSummaryByIdAsync(int id)
    {
        return await _dashboardSummaryRepository.GetDashboardSummaryByIdAsync(id);
    }

    public async Task<DashboardSummary?> CreateDashboardSummaryAsync(DashboardSummary dashboardSummary)
    {
        // Validate StaffId
        if (!dashboardSummary.StaffId.HasValue)
        {
            throw new InvalidOperationException("StaffId is required");
        }

        var staff = await _staffRepository.GetStaffByIdAsync(dashboardSummary.StaffId.Value);
        if (staff == null)
        {
            throw new InvalidOperationException("Staff not found");
        }

        // Set default values
        dashboardSummary.GeneratedDate = DateTime.UtcNow;

        // Initialize counters if not set
        dashboardSummary.TotalInjectionParticipants ??= 0;
        dashboardSummary.TotalInjectionNonParticipants ??= 0;
        dashboardSummary.InjectionParticipationRate ??= 0;
        dashboardSummary.TotalHealthCheckParticipants ??= 0;
        dashboardSummary.TotalHealthCheckNonParticipants ??= 0;
        dashboardSummary.HealthCheckParticipationRate ??= 0;
        dashboardSummary.TotalHealthEvents ??= 0;
        dashboardSummary.TotalMedicineRequests ??= 0;
        dashboardSummary.TotalAppointments ??= 0;
        dashboardSummary.ScheduledAppointments ??= 0;
        dashboardSummary.CompletedAppointments ??= 0;
        dashboardSummary.TotalMedicineItems ??= 0;
        dashboardSummary.TotalSupplyItems ??= 0;

        return await _dashboardSummaryRepository.CreateDashboardSummaryAsync(dashboardSummary);
    }

    public async Task<bool> UpdateDashboardSummaryAsync(DashboardSummary dashboardSummary)
    {
        // Validate that the summary exists
        var existingSummary = await _dashboardSummaryRepository.GetDashboardSummaryByIdAsync(dashboardSummary.SummaryId);
        if (existingSummary == null)
        {
            return false;
        }

        // Validate StaffId
        if (!dashboardSummary.StaffId.HasValue)
        {
            throw new InvalidOperationException("StaffId is required");
        }

        var staff = await _staffRepository.GetStaffByIdAsync(dashboardSummary.StaffId.Value);
        if (staff == null)
        {
            throw new InvalidOperationException("Staff not found");
        }

        return await _dashboardSummaryRepository.UpdateDashboardSummaryAsync(dashboardSummary);
    }

    public async Task<bool> DeleteDashboardSummaryAsync(int id)
    {
        return await _dashboardSummaryRepository.DeleteDashboardSummaryAsync(id);
    }

    public async Task<IEnumerable<DashboardSummary>> GetDashboardSummariesByStaffIdAsync(int staffId)
    {
        return await _dashboardSummaryRepository.GetDashboardSummariesByStaffIdAsync(staffId);
    }

    public async Task<IEnumerable<DashboardSummary>> GetDashboardSummariesByDateRangeAsync(DateTime startDate, DateTime endDate)
    {
        if (startDate > endDate)
        {
            throw new InvalidOperationException("Start date must be before end date");
        }

        return await _dashboardSummaryRepository.GetDashboardSummariesByDateRangeAsync(startDate, endDate);
    }

    public async Task<byte[]> ExportDashboardSummaryToExcelAsync(int id)
    {
        var summary = await _dashboardSummaryRepository.GetDashboardSummaryByIdAsync(id);
        if (summary == null)
        {
            throw new InvalidOperationException("Dashboard summary not found");
        }

        ExcelPackage.License.SetNonCommercialPersonal("Medical API");

        using var package = new ExcelPackage();
        var worksheet = package.Workbook.Worksheets.Add("Dashboard Summary");

        // Add summary metadata
        worksheet.Cells[1, 1].Value = "Generated Date";
        worksheet.Cells[1, 2].Value = summary.GeneratedDate?.ToString("yyyy-MM-dd HH:mm:ss");
        worksheet.Cells[2, 1].Value = "Generated By";
        worksheet.Cells[2, 2].Value = summary.Staff?.FirstName + " " + summary.Staff?.LastName;

        // Add injection statistics
        worksheet.Cells[4, 1].Value = "Injection Statistics";
        worksheet.Cells[4, 1].Style.Font.Bold = true;
        worksheet.Cells[5, 1].Value = "Total Participants";
        worksheet.Cells[5, 2].Value = summary.TotalInjectionParticipants;
        worksheet.Cells[6, 1].Value = "Total Non-Participants";
        worksheet.Cells[6, 2].Value = summary.TotalInjectionNonParticipants;
        worksheet.Cells[7, 1].Value = "Participation Rate";
        worksheet.Cells[7, 2].Value = summary.InjectionParticipationRate?.ToString("P2");

        // Add health check statistics
        worksheet.Cells[9, 1].Value = "Health Check Statistics";
        worksheet.Cells[9, 1].Style.Font.Bold = true;
        worksheet.Cells[10, 1].Value = "Total Participants";
        worksheet.Cells[10, 2].Value = summary.TotalHealthCheckParticipants;
        worksheet.Cells[11, 1].Value = "Total Non-Participants";
        worksheet.Cells[11, 2].Value = summary.TotalHealthCheckNonParticipants;
        worksheet.Cells[12, 1].Value = "Participation Rate";
        worksheet.Cells[12, 2].Value = summary.HealthCheckParticipationRate?.ToString("P2");

        // Add general statistics
        worksheet.Cells[14, 1].Value = "General Statistics";
        worksheet.Cells[14, 1].Style.Font.Bold = true;
        worksheet.Cells[15, 1].Value = "Total Health Events";
        worksheet.Cells[15, 2].Value = summary.TotalHealthEvents;
        worksheet.Cells[16, 1].Value = "Total Medicine Requests";
        worksheet.Cells[16, 2].Value = summary.TotalMedicineRequests;
        worksheet.Cells[17, 1].Value = "Total Appointments";
        worksheet.Cells[17, 2].Value = summary.TotalAppointments;
        worksheet.Cells[18, 1].Value = "Scheduled Appointments";
        worksheet.Cells[18, 2].Value = summary.ScheduledAppointments;
        worksheet.Cells[19, 1].Value = "Completed Appointments";
        worksheet.Cells[19, 2].Value = summary.CompletedAppointments;
        worksheet.Cells[20, 1].Value = "Total Medicine Items";
        worksheet.Cells[20, 2].Value = summary.TotalMedicineItems;
        worksheet.Cells[21, 1].Value = "Total Supply Items";
        worksheet.Cells[21, 2].Value = summary.TotalSupplyItems;

        // Auto-fit columns
        worksheet.Cells[worksheet.Dimension.Address].AutoFitColumns();

        return await package.GetAsByteArrayAsync();
    }
} 